### PR TITLE
Initialize project tools

### PR DESCRIPTION
**Pull request by Yousif-FJ**

### CODE REVIEW

**Comment by Yousif-FJ** [comment]
We will not follow a single project approach. Different solution will be created by Utshaw.

**Comment by Yousif-FJ** [comment]
Single project approach was followed.
This is achieved by having the dev command run the index.html file, while the build command just package the code.

**Comment by Yousif-FJ** [comment]
@rafinutshaw

**Review by lakosd — APPROVED** [review]
Approved in our in-person meeting

**Pull request merged**
